//
//  UserDetailWireframe.swift
//  ListUsers
//
//  Created by Juan Eduardo Montiel Dominguez on 02/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class UserDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init(data: UserModel) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: UserDetailViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = UserDetailInteractor()
        let presenter = UserDetailPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
        moduleViewController.data = data
    }

}

// MARK: - Extensions -

extension UserDetailWireframe: UserDetailWireframeInterface {

    func navigate(to option: UserDetailNavigationOption) {
    }
}
