//
//  UserDetailInterfaces.swift
//  ListUsers
//
//  Created by Juan Eduardo Montiel Dominguez on 02/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum UserDetailNavigationOption {
}

protocol UserDetailWireframeInterface: WireframeInterface {
    func navigate(to option: UserDetailNavigationOption)
}

protocol UserDetailViewInterface: ViewInterface {
}

protocol UserDetailPresenterInterface: PresenterInterface {
}

protocol UserDetailInteractorInterface: InteractorInterface {
}
