//
//  LoginPresenter.swift
//  ListUsers
//
//  Created by Juan Eduardo Montiel Dominguez on 01/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPresenter {

    // MARK: - Private properties -

    private unowned let _view: LoginViewInterface
    private let _wireframe: LoginWireframeInterface
    private let _interactor: LoginInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    func performLogin(user: String, password: String) {
        self._view.showLoading()
        _interactor.executeLogin(user: user, password: password) { result, error in
            if result {
                UserDefaults.standard.setValue(true, forKey: "isLogged")
                self._view.dimissLoading()
                self._view.successfullLogin()
            }else{
                self._view.dimissLoading()
                DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
                    self._view.failureLogin(message: error!)
                })
            }
        }
    }
    
    func goToMainView() {
        self._wireframe.navigate(to: .goToList)
    }
    
}
