//
//  LoginInterfaces.swift
//  ListUsers
//
//  Created by Juan Eduardo Montiel Dominguez on 01/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum LoginNavigationOption {
    case goToList
}

protocol LoginWireframeInterface: WireframeInterface {
    func navigate(to option: LoginNavigationOption)
}

protocol LoginViewInterface: ViewInterface {
    func showLoading()
    func dimissLoading()
    func successfullLogin()
    func failureLogin(message: String)
}

protocol LoginPresenterInterface: PresenterInterface {
    func performLogin(user: String, password: String)
    func goToMainView()
}

protocol LoginInteractorInterface: InteractorInterface {
    func executeLogin(user: String, password: String, callback: @escaping (Bool, String?) -> Void)
}
