//
//  ListInteractor.swift
//  ListUsers
//
//  Created by Juan Eduardo Montiel Dominguez on 02/12/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import AlamofireObjectMapper

final class ListInteractor {
}

// MARK: - Extensions -

extension ListInteractor: ListInteractorInterface {
    func executeFetchUsers(last: Int, completionHandler: @escaping ([UserModel]?, String?) -> Void) {
        
        let dic: [String: Any] = [
            "page": last,
            "results": 10,
            "seed": "smartstc",
            "nat": "ES"
        ]
        
        Alamofire.request("https://randomuser.me/api", method: .get, parameters: dic).responseObject { (response: DataResponse<UserListResponse>) in
            debugPrint(response)
            switch response.result {
            case .success(let value):
                if let results = value.results {
                    completionHandler(results,nil)
                }else{
                    completionHandler(nil, nil)
                }
            case .failure(_):
                completionHandler(nil, NSLocalizedString("internetConectionError", comment: ""))
            }

        }
    }
    
}
